name: Android CI

on:
  push:
    branches: [ main, learn ]
  pull_request:
    branches: [ main, learn ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
#          cache: gradle # ~/.gradle and ~/.m2

      - name: Download Android SDK components
        uses: android-actions/setup-android@v3

      - name: Build Debug & run unit tests
        run: ./gradlew testDebugUnitTest assembleDebug